name: TypeScript Lint and Format Check (Prettier, ESLint)

# Only triggers on PRs to the TypeScript migration branch
on:
  pull_request:
    branches:
      - ts-migration/main
    paths:
      - "instagram-ts/**"

jobs:
  format:
    name: "Validate TS formatting and lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install TS dependencies
        working-directory: instagram-ts
        run: |
          npm ci

      - name: Run Prettier check
        working-directory: instagram-ts
        run: npx prettier --check .

      - name: Run xo + tests
        working-directory: instagram-ts
        run: npm test
