# This workflow will publish the TypeScript package to NPM when a tag matching ts-v*.*.* is pushed

name: Build and Publish TypeScript Package to NPM

on:
  push:
    tags:
      # Only match formal releases (ts-v1.0.4), not beta/alpha (ts-v1.0.4-beta)
      - "ts-v[0-9]+.[0-9]+.[0-9]+"
  release:
    types: [published]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    # Only run if tag matches ts-v*.*.* pattern
    if: >
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/ts-v')) ||
      (github.event_name == 'release' && startsWith(github.event.release.tag_name, 'ts-v'))

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@i7m"

      - name: Update npm
        # Ensure npm 11.5.1 or later for trusted publishing
        run: npm install -g npm@latest

      - name: Install dependencies and build
        working-directory: ./instagram-ts
        run: npm ci && npm run build

      - name: Publish to NPM
        working-directory: ./instagram-ts
        run: npm publish --access public
